name: Daily bots
on:
  schedule:
    - cron: '0 6 * * *'   # todos los días a las 06:00 UTC (ajusta)
  workflow_dispatch:      # permite correr manualmente desde GitHub
jobs:
  run-bots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scout
        run: python bot_scout.py
        env:
          GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
          # otros secrets si necesita
      - name: Run analyzer
        run: python b_analyzer.py
      - name: Run ideator
        run: python b_ideator.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Commit outputs (opcional)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add data output || true
          git commit -m "Auto: outputs $(date -u)" || true
          git push || true
